FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .
RUN npm run build

FROM node:20-alpine

WORKDIR /app

RUN mkdir -p /app/logs && chown -R node:node /app/logs

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

USER node

EXPOSE 5000

CMD ["node", "dist/database/seeders/index.js"]
CMD ["node", "dist/index.js"]